# Generated by Django 2.2.7 on 2019-11-19 10:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191118_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
